import {
  Employee,
  Client,
  Project,
  LeaveRequest,
  Attendance,
  Meeting,
  Payment,
  InternshipApplication,
  Notification,
  ActivityLog,
} from './types';

export const mockEmployees: Employee[] = [
  {
    id: '1',
    name: 'John Anderson',
    email: 'john.anderson@asktech.com',
    phone: '+91 98765 43210',
    department: 'Engineering',
    position: 'Senior Developer',
    status: 'active',
    joinDate: '2022-01-15',
    salary: 85000,
    workingHours: 168,
    performance: 92,
  },
  {
    id: '2',
    name: 'Sarah Mitchell',
    email: 'sarah.mitchell@asktech.com',
    phone: '+91 98765 43211',
    department: 'Design',
    position: 'UX Designer',
    status: 'active',
    joinDate: '2022-03-20',
    salary: 72000,
    workingHours: 160,
    performance: 88,
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'michael.chen@asktech.com',
    phone: '+91 98765 43212',
    department: 'Engineering',
    position: 'Frontend Developer',
    status: 'on-leave',
    joinDate: '2021-11-10',
    salary: 68000,
    workingHours: 120,
    performance: 85,
  },
  {
    id: '4',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@asktech.com',
    phone: '+91 98765 43213',
    department: 'Marketing',
    position: 'Marketing Manager',
    status: 'active',
    joinDate: '2023-02-01',
    salary: 76000,
    workingHours: 165,
    performance: 90,
  },
  {
    id: '5',
    name: 'David Thompson',
    email: 'david.thompson@asktech.com',
    phone: '+91 98765 43214',
    department: 'Engineering',
    position: 'DevOps Engineer',
    status: 'active',
    joinDate: '2022-07-12',
    salary: 90000,
    workingHours: 172,
    performance: 94,
  },
  {
    id: '6',
    name: 'Priya Sharma',
    email: 'priya.sharma@asktech.com',
    phone: '+91 98765 43215',
    department: 'HR',
    position: 'HR Manager',
    status: 'active',
    joinDate: '2021-06-01',
    salary: 70000,
    workingHours: 162,
    performance: 91,
  },
  {
    id: '7',
    name: 'Rahul Gupta',
    email: 'rahul.gupta@asktech.com',
    phone: '+91 98765 43216',
    department: 'Finance',
    position: 'Finance Analyst',
    status: 'active',
    joinDate: '2023-05-10',
    salary: 65000,
    workingHours: 155,
    performance: 87,
  },
  {
    id: '8',
    name: 'Anika Patel',
    email: 'anika.patel@asktech.com',
    phone: '+91 98765 43217',
    department: 'Engineering',
    position: 'Backend Developer',
    status: 'suspended',
    joinDate: '2022-09-01',
    salary: 78000,
    workingHours: 0,
    performance: 76,
  },
];

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Robert Williams',
    company: 'TechCorp Industries',
    email: 'robert@techcorp.com',
    phone: '+1 (555) 123-4567',
    status: 'active',
    projectsCount: 3,
    totalValue: 145000,
    country: 'USA',
    joinedDate: '2023-01-10',
  },
  {
    id: '2',
    name: 'Jessica Brown',
    company: 'Digital Innovations',
    email: 'jessica@digitalinno.com',
    phone: '+1 (555) 234-5678',
    status: 'active',
    projectsCount: 2,
    totalValue: 89000,
    country: 'UK',
    joinedDate: '2023-04-05',
  },
  {
    id: '3',
    name: 'William Davis',
    company: 'StartUp Hub',
    email: 'william@startuphub.com',
    phone: '+1 (555) 345-6789',
    status: 'pending',
    projectsCount: 1,
    totalValue: 52000,
    country: 'Canada',
    joinedDate: '2024-01-20',
  },
  {
    id: '4',
    name: 'Jennifer Wilson',
    company: 'Enterprise Solutions',
    email: 'jennifer@enterprise.com',
    phone: '+1 (555) 456-7890',
    status: 'active',
    projectsCount: 4,
    totalValue: 234000,
    country: 'Australia',
    joinedDate: '2022-11-15',
  },
  {
    id: '5',
    name: 'James Martinez',
    company: 'Cloud Systems',
    email: 'james@cloudsys.com',
    phone: '+1 (555) 567-8901',
    status: 'inactive',
    projectsCount: 0,
    totalValue: 0,
    country: 'UAE',
    joinedDate: '2023-08-30',
  },
  {
    id: '6',
    name: 'Anjali Mehta',
    company: 'Infinity Corp',
    email: 'anjali@infinitycorp.in',
    phone: '+91 99887 76655',
    status: 'active',
    projectsCount: 2,
    totalValue: 67000,
    country: 'India',
    joinedDate: '2024-03-01',
  },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'E-commerce Platform Redesign',
    client: 'TechCorp Industries',
    clientId: '1',
    status: 'in-progress',
    progress: 75,
    startDate: '2026-03-01',
    endDate: '2026-06-30',
    budget: 85000,
    spent: 63750,
    team: ['John Anderson', 'Sarah Mitchell', 'Michael Chen'],
    description: 'Complete redesign of the TechCorp e-commerce platform with modern UI/UX.',
    priority: 'high',
    milestones: [
      { id: 'm1', title: 'UI Wireframes', dueDate: '2026-03-15', completed: true },
      { id: 'm2', title: 'Frontend Development', dueDate: '2026-04-30', completed: true },
      { id: 'm3', title: 'Backend Integration', dueDate: '2026-05-31', completed: false },
      { id: 'm4', title: 'Testing & Launch', dueDate: '2026-06-30', completed: false },
    ],
  },
  {
    id: '2',
    name: 'Mobile App Development',
    client: 'Digital Innovations',
    clientId: '2',
    status: 'in-progress',
    progress: 60,
    startDate: '2026-04-15',
    endDate: '2026-08-15',
    budget: 120000,
    spent: 72000,
    team: ['David Thompson', 'Emily Rodriguez'],
    description: 'Cross-platform mobile application for Digital Innovations.',
    priority: 'critical',
    milestones: [
      { id: 'm1', title: 'Requirements & Design', dueDate: '2026-04-30', completed: true },
      { id: 'm2', title: 'Core Feature Development', dueDate: '2026-06-30', completed: false },
      { id: 'm3', title: 'QA & Testing', dueDate: '2026-07-31', completed: false },
      { id: 'm4', title: 'App Store Submission', dueDate: '2026-08-15', completed: false },
    ],
  },
  {
    id: '3',
    name: 'CRM System Integration',
    client: 'Enterprise Solutions',
    clientId: '4',
    status: 'planning',
    progress: 15,
    startDate: '2026-05-01',
    endDate: '2026-09-30',
    budget: 95000,
    spent: 14250,
    team: ['John Anderson'],
    description: 'Full CRM system integration with existing enterprise infrastructure.',
    priority: 'medium',
    milestones: [
      { id: 'm1', title: 'Architecture Design', dueDate: '2026-05-20', completed: false },
      { id: 'm2', title: 'API Development', dueDate: '2026-07-15', completed: false },
    ],
  },
  {
    id: '4',
    name: 'Website Development',
    client: 'StartUp Hub',
    clientId: '3',
    status: 'completed',
    progress: 100,
    startDate: '2026-01-10',
    endDate: '2026-03-20',
    budget: 45000,
    spent: 43200,
    team: ['Sarah Mitchell', 'Michael Chen'],
    description: 'Corporate website development for StartUp Hub.',
    priority: 'low',
    milestones: [
      { id: 'm1', title: 'Design', dueDate: '2026-01-31', completed: true },
      { id: 'm2', title: 'Development', dueDate: '2026-02-28', completed: true },
      { id: 'm3', title: 'Launch', dueDate: '2026-03-20', completed: true },
    ],
  },
  {
    id: '5',
    name: 'AI Analytics Dashboard',
    client: 'Infinity Corp',
    clientId: '6',
    status: 'delayed',
    progress: 40,
    startDate: '2026-02-01',
    endDate: '2026-05-01',
    budget: 67000,
    spent: 40200,
    team: ['David Thompson', 'Rahul Gupta'],
    description: 'AI-powered analytics dashboard for business intelligence.',
    priority: 'high',
    milestones: [
      { id: 'm1', title: 'Data Architecture', dueDate: '2026-02-28', completed: true },
      { id: 'm2', title: 'ML Model Integration', dueDate: '2026-04-01', completed: false },
    ],
  },
];

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: '1',
    employeeId: '3',
    employeeName: 'Michael Chen',
    type: 'sick',
    startDate: '2026-05-20',
    endDate: '2026-05-22',
    days: 3,
    reason: 'Medical appointment and recovery',
    status: 'approved',
    appliedDate: '2026-05-18',
    approvedBy: 'Priya Sharma',
  },
  {
    id: '2',
    employeeId: '1',
    employeeName: 'John Anderson',
    type: 'annual',
    startDate: '2026-06-10',
    endDate: '2026-06-17',
    days: 5,
    reason: 'Family vacation',
    status: 'pending',
    appliedDate: '2026-05-15',
  },
  {
    id: '3',
    employeeId: '4',
    employeeName: 'Emily Rodriguez',
    type: 'casual',
    startDate: '2026-05-18',
    endDate: '2026-05-18',
    days: 1,
    reason: 'Personal matter',
    status: 'approved',
    appliedDate: '2026-05-17',
    approvedBy: 'Priya Sharma',
  },
  {
    id: '4',
    employeeId: '7',
    employeeName: 'Rahul Gupta',
    type: 'casual',
    startDate: '2026-05-25',
    endDate: '2026-05-26',
    days: 2,
    reason: 'Family function',
    status: 'pending',
    appliedDate: '2026-05-16',
  },
  {
    id: '5',
    employeeId: '2',
    employeeName: 'Sarah Mitchell',
    type: 'sick',
    startDate: '2026-04-12',
    endDate: '2026-04-13',
    days: 2,
    reason: 'Fever and cold',
    status: 'rejected',
    appliedDate: '2026-04-11',
    approvedBy: 'Priya Sharma',
  },
];

export const mockAttendance: Attendance[] = [
  { id: '1', employeeId: '1', employeeName: 'John Anderson', date: '2026-05-18', checkIn: '09:00', checkOut: '18:00', status: 'present', workingHours: 9 },
  { id: '2', employeeId: '2', employeeName: 'Sarah Mitchell', date: '2026-05-18', checkIn: '09:15', checkOut: '18:30', status: 'late', workingHours: 9.25 },
  { id: '3', employeeId: '3', employeeName: 'Michael Chen', date: '2026-05-18', checkIn: '-', checkOut: '-', status: 'absent', workingHours: 0 },
  { id: '4', employeeId: '4', employeeName: 'Emily Rodriguez', date: '2026-05-18', checkIn: '08:45', checkOut: '17:30', status: 'present', workingHours: 8.75 },
  { id: '5', employeeId: '5', employeeName: 'David Thompson', date: '2026-05-18', checkIn: '08:30', checkOut: '18:00', status: 'present', workingHours: 9.5 },
  { id: '6', employeeId: '6', employeeName: 'Priya Sharma', date: '2026-05-18', checkIn: '09:00', checkOut: '13:30', status: 'half-day', workingHours: 4.5 },
  { id: '7', employeeId: '7', employeeName: 'Rahul Gupta', date: '2026-05-18', checkIn: '09:00', checkOut: '18:00', status: 'present', workingHours: 9 },
  { id: '8', employeeId: '8', employeeName: 'Anika Patel', date: '2026-05-18', checkIn: '-', checkOut: '-', status: 'absent', workingHours: 0 },
];

export const mockMeetings: Meeting[] = [
  {
    id: '1',
    title: 'Q2 Project Review',
    description: 'Quarterly review of all active projects and performance metrics.',
    date: '2026-05-20',
    time: '10:00',
    duration: '2h',
    type: 'internal',
    status: 'scheduled',
    attendees: ['John Anderson', 'Sarah Mitchell', 'David Thompson', 'Emily Rodriguez'],
    location: 'Conference Room A',
    organizer: 'Priya Sharma',
  },
  {
    id: '2',
    title: 'TechCorp Platform Demo',
    description: 'Live demo of e-commerce platform progress to client.',
    date: '2026-05-21',
    time: '14:00',
    duration: '1h 30m',
    type: 'client',
    status: 'scheduled',
    attendees: ['John Anderson', 'Sarah Mitchell', 'Robert Williams'],
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    organizer: 'John Anderson',
  },
  {
    id: '3',
    title: 'Frontend Developer Interview',
    description: 'Technical interview for Frontend Developer position.',
    date: '2026-05-19',
    time: '11:00',
    duration: '1h',
    type: 'interview',
    status: 'completed',
    attendees: ['Priya Sharma', 'Michael Chen'],
    location: 'HR Office',
    organizer: 'Priya Sharma',
  },
  {
    id: '4',
    title: 'Engineering Team Sync',
    description: 'Weekly engineering team sync to discuss blockers and progress.',
    date: '2026-05-22',
    time: '09:30',
    duration: '45m',
    type: 'team',
    status: 'scheduled',
    attendees: ['John Anderson', 'Michael Chen', 'David Thompson', 'Anika Patel'],
    meetingLink: 'https://zoom.us/j/123456789',
    organizer: 'John Anderson',
  },
  {
    id: '5',
    title: 'Digital Innovations Status Update',
    description: 'Monthly status update with Digital Innovations client.',
    date: '2026-05-18',
    time: '16:00',
    duration: '1h',
    type: 'client',
    status: 'completed',
    attendees: ['Emily Rodriguez', 'David Thompson', 'Jessica Brown'],
    meetingLink: 'https://teams.microsoft.com/l/meetup-join',
    organizer: 'Emily Rodriguez',
  },
];

export const mockPayments: Payment[] = [
  {
    id: '1',
    invoiceNumber: 'INV-2026-001',
    clientId: '1',
    clientName: 'TechCorp Industries',
    projectName: 'E-commerce Platform Redesign',
    amount: 42500,
    status: 'paid',
    dueDate: '2026-04-30',
    paidDate: '2026-04-25',
    paymentMethod: 'bank-transfer',
    description: 'Milestone 1 & 2 payment',
  },
  {
    id: '2',
    invoiceNumber: 'INV-2026-002',
    clientId: '2',
    clientName: 'Digital Innovations',
    projectName: 'Mobile App Development',
    amount: 36000,
    status: 'paid',
    dueDate: '2026-05-15',
    paidDate: '2026-05-12',
    paymentMethod: 'card',
    description: 'Phase 1 completion payment',
  },
  {
    id: '3',
    invoiceNumber: 'INV-2026-003',
    clientId: '4',
    clientName: 'Enterprise Solutions',
    projectName: 'CRM System Integration',
    amount: 23750,
    status: 'pending',
    dueDate: '2026-05-25',
    description: 'Initial deposit and requirements phase',
  },
  {
    id: '4',
    invoiceNumber: 'INV-2026-004',
    clientId: '6',
    clientName: 'Infinity Corp',
    projectName: 'AI Analytics Dashboard',
    amount: 40200,
    status: 'overdue',
    dueDate: '2026-05-10',
    description: 'Phase 1 & 2 payment',
  },
  {
    id: '5',
    invoiceNumber: 'INV-2026-005',
    clientId: '3',
    clientName: 'StartUp Hub',
    projectName: 'Website Development',
    amount: 45000,
    status: 'paid',
    dueDate: '2026-03-25',
    paidDate: '2026-03-22',
    paymentMethod: 'upi',
    description: 'Full project payment on completion',
  },
  {
    id: '6',
    invoiceNumber: 'INV-2026-006',
    clientId: '1',
    clientName: 'TechCorp Industries',
    projectName: 'E-commerce Platform Redesign',
    amount: 42500,
    status: 'pending',
    dueDate: '2026-06-15',
    description: 'Milestone 3 & 4 payment',
  },
];

export const mockInternships: InternshipApplication[] = [
  {
    id: '1',
    candidateName: 'Arjun Verma',
    email: 'arjun.verma@gmail.com',
    phone: '+91 99001 12233',
    domain: 'Frontend Development',
    status: 'interview-scheduled',
    appliedDate: '2026-05-01',
    interviewDate: '2026-05-22',
    college: 'IIT Delhi',
    skills: ['React', 'TypeScript', 'CSS'],
    experience: 'Fresher',
    notes: 'Strong portfolio with 3 personal projects',
  },
  {
    id: '2',
    candidateName: 'Meera Nair',
    email: 'meera.nair@gmail.com',
    phone: '+91 99001 22344',
    domain: 'UI/UX Design',
    status: 'under-review',
    appliedDate: '2026-05-05',
    college: 'NID Ahmedabad',
    skills: ['Figma', 'Adobe XD', 'Sketch'],
    experience: 'Fresher',
  },
  {
    id: '3',
    candidateName: 'Karan Singh',
    email: 'karan.singh@gmail.com',
    phone: '+91 99001 33455',
    domain: 'Backend Development',
    status: 'selected',
    appliedDate: '2026-04-20',
    interviewDate: '2026-05-05',
    college: 'BITS Pilani',
    skills: ['Node.js', 'MongoDB', 'Go'],
    experience: '6 months',
    notes: 'Excellent technical skills, strong Go knowledge',
  },
  {
    id: '4',
    candidateName: 'Shreya Kapoor',
    email: 'shreya.kapoor@gmail.com',
    phone: '+91 99001 44566',
    domain: 'Digital Marketing',
    status: 'applied',
    appliedDate: '2026-05-10',
    college: 'Delhi University',
    skills: ['SEO', 'Google Ads', 'Content Writing'],
    experience: 'Fresher',
  },
  {
    id: '5',
    candidateName: 'Rohan Desai',
    email: 'rohan.desai@gmail.com',
    phone: '+91 99001 55677',
    domain: 'Mobile Development',
    status: 'rejected',
    appliedDate: '2026-04-15',
    interviewDate: '2026-04-28',
    college: 'VIT Vellore',
    skills: ['Flutter', 'React Native'],
    experience: 'Fresher',
    notes: 'Good attitude but lacks practical experience',
  },
  {
    id: '6',
    candidateName: 'Divya Rao',
    email: 'divya.rao@gmail.com',
    phone: '+91 99001 66788',
    domain: 'Data Science',
    status: 'interview-scheduled',
    appliedDate: '2026-05-08',
    interviewDate: '2026-05-23',
    college: 'IISc Bangalore',
    skills: ['Python', 'TensorFlow', 'SQL', 'Pandas'],
    experience: '1 year',
    notes: 'Strong ML background',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'New Leave Request',
    message: 'John Anderson has submitted a leave request for June 10-17.',
    type: 'info',
    read: false,
    timestamp: '2026-05-18T14:30:00Z',
    link: '/leaves',
  },
  {
    id: '2',
    title: 'Payment Overdue',
    message: 'Invoice INV-2026-004 from Infinity Corp is overdue by 8 days.',
    type: 'error',
    read: false,
    timestamp: '2026-05-18T10:00:00Z',
    link: '/payments',
  },
  {
    id: '3',
    title: 'Project Milestone Completed',
    message: 'E-commerce Platform Redesign - Frontend Development milestone completed.',
    type: 'success',
    read: false,
    timestamp: '2026-05-17T16:00:00Z',
    link: '/projects',
  },
  {
    id: '4',
    title: 'New Internship Application',
    message: 'Shreya Kapoor applied for Digital Marketing internship.',
    type: 'info',
    read: true,
    timestamp: '2026-05-16T09:00:00Z',
    link: '/internships',
  },
  {
    id: '5',
    title: 'Meeting Reminder',
    message: 'Q2 Project Review meeting tomorrow at 10:00 AM.',
    type: 'warning',
    read: true,
    timestamp: '2026-05-17T18:00:00Z',
    link: '/meetings',
  },
  {
    id: '6',
    title: 'Employee Suspended',
    message: 'Anika Patel account has been suspended pending HR review.',
    type: 'warning',
    read: true,
    timestamp: '2026-05-15T11:00:00Z',
    link: '/employees',
  },
];

export const mockActivityLogs: ActivityLog[] = [
  {
    id: '1',
    userId: 'admin',
    userName: 'Admin User',
    action: 'Approved leave request for Michael Chen',
    module: 'Leave Management',
    timestamp: '2026-05-18T14:35:00Z',
    ipAddress: '192.168.1.1',
    device: 'Chrome / Windows',
  },
  {
    id: '2',
    userId: 'admin',
    userName: 'Admin User',
    action: 'Created new project: AI Analytics Dashboard',
    module: 'Project Management',
    timestamp: '2026-05-18T11:20:00Z',
    ipAddress: '192.168.1.1',
    device: 'Chrome / Windows',
  },
  {
    id: '3',
    userId: 'admin',
    userName: 'Admin User',
    action: 'Added new client: Anjali Mehta (Infinity Corp)',
    module: 'Client Management',
    timestamp: '2026-05-17T16:45:00Z',
    ipAddress: '192.168.1.1',
    device: 'Chrome / Windows',
  },
  {
    id: '4',
    userId: 'admin',
    userName: 'Admin User',
    action: 'Scheduled interview for Arjun Verma',
    module: 'Internship Management',
    timestamp: '2026-05-17T10:15:00Z',
    ipAddress: '192.168.1.1',
    device: 'Safari / macOS',
  },
  {
    id: '5',
    userId: 'admin',
    userName: 'Admin User',
    action: 'Marked invoice INV-2026-005 as paid',
    module: 'Payments',
    timestamp: '2026-05-16T14:00:00Z',
    ipAddress: '192.168.1.2',
    device: 'Chrome / Windows',
  },
];

// Revenue chart data
export const revenueChartData = [
  { month: 'Jan', revenue: 32000, expenses: 18000, profit: 14000 },
  { month: 'Feb', revenue: 45000, expenses: 22000, profit: 23000 },
  { month: 'Mar', revenue: 38000, expenses: 19000, profit: 19000 },
  { month: 'Apr', revenue: 52000, expenses: 25000, profit: 27000 },
  { month: 'May', revenue: 61000, expenses: 28000, profit: 33000 },
  { month: 'Jun', revenue: 58000, expenses: 26000, profit: 32000 },
];

// Attendance trend data
export const attendanceTrendData = [
  { month: 'Jan', present: 88, absent: 8, late: 4 },
  { month: 'Feb', present: 85, absent: 10, late: 5 },
  { month: 'Mar', present: 90, absent: 7, late: 3 },
  { month: 'Apr', present: 87, absent: 9, late: 4 },
  { month: 'May', present: 92, absent: 5, late: 3 },
  { month: 'Jun', present: 89, absent: 8, late: 3 },
];

// Project status distribution
export const projectStatusData = [
  { name: 'In Progress', value: 8, color: '#3b82f6' },
  { name: 'Completed', value: 12, color: '#22c55e' },
  { name: 'Planning', value: 4, color: '#f59e0b' },
  { name: 'Delayed', value: 2, color: '#ef4444' },
  { name: 'On Hold', value: 2, color: '#8b5cf6' },
];
