import { Employee, Client, Project, LeaveRequest, Attendance } from './types';

export const mockEmployees: Employee[] = [
  {
    id: '1',
    name: 'John Anderson',
    email: 'john.anderson@asktech.com',
    department: 'Engineering',
    position: 'Senior Developer',
    status: 'active',
    joinDate: '2022-01-15',
  },
  {
    id: '2',
    name: 'Sarah Mitchell',
    email: 'sarah.mitchell@asktech.com',
    department: 'Design',
    position: 'UX Designer',
    status: 'active',
    joinDate: '2022-03-20',
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'michael.chen@asktech.com',
    department: 'Engineering',
    position: 'Frontend Developer',
    status: 'on-leave',
    joinDate: '2021-11-10',
  },
  {
    id: '4',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@asktech.com',
    department: 'Marketing',
    position: 'Marketing Manager',
    status: 'active',
    joinDate: '2023-02-01',
  },
  {
    id: '5',
    name: 'David Thompson',
    email: 'david.thompson@asktech.com',
    department: 'Engineering',
    position: 'DevOps Engineer',
    status: 'active',
    joinDate: '2022-07-12',
  },
];

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Robert Williams',
    company: 'TechCorp Industries',
    email: 'robert@techcorp.com',
    phone: '+1 (555) 123-4567',
    status: 'active',
    projectsCount: 3,
    totalValue: 145000,
  },
  {
    id: '2',
    name: 'Jessica Brown',
    company: 'Digital Innovations',
    email: 'jessica@digitalinno.com',
    phone: '+1 (555) 234-5678',
    status: 'active',
    projectsCount: 2,
    totalValue: 89000,
  },
  {
    id: '3',
    name: 'William Davis',
    company: 'StartUp Hub',
    email: 'william@startuphub.com',
    phone: '+1 (555) 345-6789',
    status: 'pending',
    projectsCount: 1,
    totalValue: 52000,
  },
  {
    id: '4',
    name: 'Jennifer Wilson',
    company: 'Enterprise Solutions',
    email: 'jennifer@enterprise.com',
    phone: '+1 (555) 456-7890',
    status: 'active',
    projectsCount: 4,
    totalValue: 234000,
  },
  {
    id: '5',
    name: 'James Martinez',
    company: 'Cloud Systems',
    email: 'james@cloudsys.com',
    phone: '+1 (555) 567-8901',
    status: 'inactive',
    projectsCount: 0,
    totalValue: 0,
  },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'E-commerce Platform Redesign',
    client: 'TechCorp Industries',
    status: 'in-progress',
    progress: 75,
    startDate: '2026-03-01',
    endDate: '2026-06-30',
    budget: 85000,
    team: ['John Anderson', 'Sarah Mitchell', 'Michael Chen'],
  },
  {
    id: '2',
    name: 'Mobile App Development',
    client: 'Digital Innovations',
    status: 'in-progress',
    progress: 60,
    startDate: '2026-04-15',
    endDate: '2026-08-15',
    budget: 120000,
    team: ['David Thompson', 'Emily Rodriguez'],
  },
  {
    id: '3',
    name: 'CRM System Integration',
    client: 'Enterprise Solutions',
    status: 'planning',
    progress: 15,
    startDate: '2026-05-01',
    endDate: '2026-09-30',
    budget: 95000,
    team: ['John Anderson'],
  },
  {
    id: '4',
    name: 'Website Development',
    client: 'StartUp Hub',
    status: 'completed',
    progress: 100,
    startDate: '2026-01-10',
    endDate: '2026-03-20',
    budget: 45000,
    team: ['Sarah Mitchell', 'Michael Chen'],
  },
];

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: '1',
    employeeId: '3',
    employeeName: 'Michael Chen',
    type: 'sick',
    startDate: '2026-05-20',
    endDate: '2026-05-22',
    days: 3,
    reason: 'Medical appointment and recovery',
    status: 'approved',
  },
  {
    id: '2',
    employeeId: '1',
    employeeName: 'John Anderson',
    type: 'annual',
    startDate: '2026-06-10',
    endDate: '2026-06-17',
    days: 5,
    reason: 'Family vacation',
    status: 'pending',
  },
  {
    id: '3',
    employeeId: '4',
    employeeName: 'Emily Rodriguez',
    type: 'casual',
    startDate: '2026-05-18',
    endDate: '2026-05-18',
    days: 1,
    reason: 'Personal matter',
    status: 'approved',
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: '1',
    employeeId: '1',
    date: '2026-05-15',
    checkIn: '09:00',
    checkOut: '18:00',
    status: 'present',
  },
  {
    id: '2',
    employeeId: '2',
    date: '2026-05-15',
    checkIn: '09:15',
    checkOut: '18:30',
    status: 'late',
  },
  {
    id: '3',
    employeeId: '3',
    date: '2026-05-15',
    checkIn: '-',
    checkOut: '-',
    status: 'absent',
  },
];
